name: souvenir
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  video_player: ^2.9.5
  audioplayers: ^6.4.0
  firebase_core: ^3.13.0
  get: ^4.7.2
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  dots_indicator: ^4.0.1
  uuid: ^4.5.1
  firebase_storage: ^12.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/
