// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjIbtZpWBcqK6VU9REOrq_rbuz2gBv0dg',
    appId: '1:968467385575:web:f7e2908b25eb2627bde642',
    messagingSenderId: '968467385575',
    projectId: 'souvenir-1638a',
    authDomain: 'souvenir-1638a.firebaseapp.com',
    storageBucket: 'souvenir-1638a.firebasestorage.app',
    measurementId: 'G-JCY3C7VZDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdaFbGql7Q_zU4MX2mBNQoths1MLC3eiI',
    appId: '1:968467385575:android:4f5a2cebf668cc9abde642',
    messagingSenderId: '968467385575',
    projectId: 'souvenir-1638a',
    storageBucket: 'souvenir-1638a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQzXE5Q2ySqCdENgFvJfDNKxbIEYZ70AA',
    appId: '1:968467385575:ios:6f153370054ca1d7bde642',
    messagingSenderId: '968467385575',
    projectId: 'souvenir-1638a',
    storageBucket: 'souvenir-1638a.firebasestorage.app',
    iosBundleId: 'com.example.souvenir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQzXE5Q2ySqCdENgFvJfDNKxbIEYZ70AA',
    appId: '1:968467385575:ios:6f153370054ca1d7bde642',
    messagingSenderId: '968467385575',
    projectId: 'souvenir-1638a',
    storageBucket: 'souvenir-1638a.firebasestorage.app',
    iosBundleId: 'com.example.souvenir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjIbtZpWBcqK6VU9REOrq_rbuz2gBv0dg',
    appId: '1:968467385575:web:5e1a42f409603006bde642',
    messagingSenderId: '968467385575',
    projectId: 'souvenir-1638a',
    authDomain: 'souvenir-1638a.firebaseapp.com',
    storageBucket: 'souvenir-1638a.firebasestorage.app',
    measurementId: 'G-FQSDX0SC8H',
  );
}
